spring:
  application:
    name: Mapping-tutorial

  datasource:
    url: jdbc:mysql://localhost:3306/mappingtutorial
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#logging:
#  level:
#    root: DEBUG

# spring actuator configuration
management:
  endpoints:
    web:
      exposure.include: "*"
#      /health/info endpoint information
  info:
    git:
      enabled: true
    build:
      enabled: true
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true