spring:
  application:
    name: Mapping-tutorial

  datasource:
    url: jdbc:mysql://localhost:3306/mappingtutorial
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true